K2 Report Addition
tpcarman/As-Built-Report pull request #51
Opened 2018-11-01 19:46 UTC by Midnigh7

Addition of a Kaminario K2 Storage Report.

## Description
Addition of a K2 Storage report and style.

## Related Issue

## Motivation and Context
Added another SAN provider for reporting against.

## How Has This Been Tested?
Tested report against several K2 appliances.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ X] My code follows the code style of this project.
- [ ]X My change requires a change to the documentation.
- [ X] I have updated the documentation accordingly.
- [ X] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.

2018-11-02 03:22 UTC, Midnigh7 commented
Added K2 Storage Report.
Added VM IP and PortGroup.

2018-11-12 05:13 UTC, tpcarman requested changes
Hi @Midnigh7,
Thank you for contributing a new report. We are working towards implementing some script guidelines as well as refactoring our current scripts to allow a move to a PS module. In preparation for this, could you please review my comments and implement the changes as requested. I will provide further information on the required changes to refactor your script as a PS module once we are closer to a release.
Thanks.

2018-11-12 05:13 UTC, tpcarman commented on Src/Public/Reports/K2/k2.ps1
> +$K2Arrays = $Target.split(",")
You shouldn't need to split the array as this will be done in base script `New-AsBuiltReport.ps1`.
``[Parameter(Position = 0, Mandatory = $True, HelpMessage = 'Please provide the IP/FQDN of the system')]
    [ValidateNotNullOrEmpty()]
    [Alias('Cluster', 'Server', 'IP')]
    [String[]]$Target,``

2018-11-12 05:13 UTC, tpcarman commented on Src/Public/Reports/K2/k2.ps1
> +foreach ($Endpoint in $K2Arrays) {
``foreach ($Endpoint in $Target) {``

2018-11-12 05:13 UTC, tpcarman commented on Src/Public/Reports/K2/k2.ps1
> +                $ArraySummary = Get-K2State | Sort-Object array_name | Select-Object @{L = 'System Name'; E = {$_.system_name}}, @{L = 'Version'; E = {$_.system_version}},
We are working to improve readability and consistency in existing scripts, so we are moving to using PSCustomObjects, for eaxample;
``$Array = Get-K2State | Sort-Object array_name
$ArraySummary = [PSCustomObject] @ {
    'System Name' = $Array.system_name
    'Version' = $Array.system_version
    'Connectivity Type' = $Array.system_connectivity_type
    'System State' = $Array.state
}
$ArraySummary | Table -Name 'Array Summary'``

Could you please update your script to follow these new guidelines.

2018-11-12 05:13 UTC, tpcarman commented on Src/Public/Reports/vSphere/vSphere.ps1
> -                                @{L = 'vNICs'; E = {($_.ExtensionData.Config.Hardware.Device | Where-Object {$_ -is [VMware.Vim.VirtualEthernetCard]}).Count}}, Notes
Please remove this commit as I am working on incorporating some of your suggestions, as well as others. in an upcoming update of the vSphere report.

2019-01-29 08:55 UTC, tpcarman commented
Requested changes have not been implemented. This pull request will now be closed.

2019-01-29 08:55 UTC, closed without merging